# Generated by Django 2.2.6 on 2020-05-24 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_borrower'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LoanApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loanDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LendedAmt', models.IntegerField()),
                ('MonthlyEMI', models.IntegerField()),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('loanID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.Borrower')),
            ],
        ),
    ]
