# Generated by Django 2.2.6 on 2020-05-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='CreditScore',
        ),
    ]
